// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class CommentaireVM
    {
        public CommentaireVM()
        {
            Notification = new HashSet<NotificationVM>();
        }

        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public DateTime? DateCreation { get; set; }
        public int? RessourceId { get; set; }
        public int? UtilisateurId { get; set; }

        public virtual RessourceVM Ressource { get; set; }
        public virtual UtilisateurVM Utilisateur { get; set; }
        public virtual ICollection<NotificationVM> Notification { get; set; }
    }
}