// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class CompetenceVM
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string Niveau { get; set; }
        public int? UtilisateurId { get; set; }

        public virtual UtilisateurVM Utilisateur { get; set; }
    }
}