// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class NotificationVM
    {
        public int Id { get; set; }
        public int? ProjetId { get; set; }
        public int? RessourceId { get; set; }
        public int? CommentaireId { get; set; }
        public string Status { get; set; }

        public virtual CommentaireVM Commentaire { get; set; }
        public virtual ProjetVM Projet { get; set; }
        public virtual RessourceVM Ressource { get; set; }
    }
}