// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class PrivilegeparroleVM
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int PrivilegeId { get; set; }

        public virtual PrivilegeVM Privilege { get; set; }
        public virtual RoleVM Role { get; set; }
    }
}