// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class PrivilegeVM
    {
        public PrivilegeVM()
        {
            Privilegeparrole = new HashSet<PrivilegeparroleVM>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public DateTime? DateCreation { get; set; }

        public virtual ICollection<PrivilegeparroleVM> Privilegeparrole { get; set; }
    }
}