// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class ProjetVM
    {
        public ProjetVM()
        {
            Notification = new HashSet<NotificationVM>();
            Ressource = new HashSet<RessourceVM>();
        }

        public int Id { get; set; }
        public string Libelle { get; set; }
        public int? Duree { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Enonce { get; set; }
        public string PieceJointe { get; set; }
        public int? UtilisateurId { get; set; }

        public virtual UtilisateurVM Utilisateur { get; set; }
        public virtual ICollection<NotificationVM> Notification { get; set; }
        public virtual ICollection<RessourceVM> Ressource { get; set; }
    }
}