// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class ReferencielVM
    {
        public ReferencielVM()
        {
            Promo = new HashSet<PromoVM>();
        }

        public int Id { get; set; }
        public string Libelle { get; set; }

        public virtual ICollection<PromoVM> Promo { get; set; }
    }
}