// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class RessourceVM
    {
        public RessourceVM()
        {
            Commentaire = new HashSet<CommentaireVM>();
            Notification = new HashSet<NotificationVM>();
        }

        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int? ProjetId { get; set; }
        public int? UtilisateurId { get; set; }

        public virtual ProjetVM Projet { get; set; }
        public virtual UtilisateurVM Utilisateur { get; set; }
        public virtual ICollection<CommentaireVM> Commentaire { get; set; }
        public virtual ICollection<NotificationVM> Notification { get; set; }
    }
}