// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models.CollectionViewModel
{
    public partial class UtilisateurparreferencielVM
    {
        public int Id { get; set; }
        public int UtilisateurId { get; set; }
        public int ReferencielId { get; set; }
        public DateTime? DateCreation { get; set; }
    }
}