// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models
{
    public partial class Notification
    {
        public int Id { get; set; }
        public int? ProjetId { get; set; }
        public int? RessourceId { get; set; }
        public int? CommentaireId { get; set; }
        public string Status { get; set; }

        public virtual Commentaire Commentaire { get; set; }
        public virtual Projet Projet { get; set; }
        public virtual Ressource Ressource { get; set; }
    }
}