// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models
{
    public partial class Promo
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Image { get; set; }
        public string Lieu { get; set; }
        public string Description { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public int? ReferentielId { get; set; }

        public virtual Referenciel Referentiel { get; set; }
    }
}