// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models
{
    public partial class Referenciel
    {
        public Referenciel()
        {
            Promo = new HashSet<Promo>();
            Utilisateurparreferenciel = new HashSet<Utilisateurparreferenciel>();
        }

        public int Id { get; set; }
        public string Libelle { get; set; }

        public virtual ICollection<Promo> Promo { get; set; }
        public virtual ICollection<Utilisateurparreferenciel> Utilisateurparreferenciel { get; set; }
    }
}