// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models
{
    public partial class Ressource
    {
        public Ressource()
        {
            Commentaire = new HashSet<Commentaire>();
            Notification = new HashSet<Notification>();
        }

        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int? ProjetId { get; set; }
        public int? UtilisateurId { get; set; }

        public virtual Projet Projet { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<Commentaire> Commentaire { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
    }
}