// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PGSFORM.Models
{
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            Commentaire = new HashSet<Commentaire>();
            Competence = new HashSet<Competence>();
            Projet = new HashSet<Projet>();
            Ressource = new HashSet<Ressource>();
            Utilisateurparreferenciel = new HashSet<Utilisateurparreferenciel>();
        }

        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public DateTime DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
        public int Telephone { get; set; }
        public string Email { get; set; }
        public int RoleId { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Commentaire> Commentaire { get; set; }
        public virtual ICollection<Competence> Competence { get; set; }
        public virtual ICollection<Projet> Projet { get; set; }
        public virtual ICollection<Ressource> Ressource { get; set; }
        public virtual ICollection<Utilisateurparreferenciel> Utilisateurparreferenciel { get; set; }
    }
}